# EVN

In [19]:
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf

# 행렬연산

## 데이터

In [ ]:
hidden = np.random.randint(-9, 10, (5, 4)) / 10
hidden

## element wise sum

In [4]:
arg = np.random.randint(-9, 10, (5, 4)) / 10
arg, hidden + arg

(array([[-0.1,  0.7, -0.1, -0.3],
        [-0.5, -0.7, -0.6, -0.5],
        [-0.2,  0.5,  0.7,  0.7],
        [ 0. ,  0.4,  0.6, -0.6],
        [-0.7, -0.7,  0.5,  0.9]]), array([[ 0.6,  0. , -0.8, -1.1],
        [-0.2, -1.5,  0. , -0.8],
        [-0.5,  0.1,  0.7,  0.1],
        [ 0.8,  1.3,  0.8, -0.6],
        [-0.8,  0. ,  0.9,  0.6]]))

In [21]:
arg = np.random.randint(-9, 10, (1, 4)) / 10
arg, hidden + arg

(array([[-0.1,  0.5, -0.3,  0.1]]), array([[ 0.7,  0.6,  0.4,  0. ],
        [-0.1,  0.8, -0.7,  0.6],
        [ 0.5,  0.6, -0.1,  0.3],
        [-0.2,  0.7, -1. ,  0.3],
        [ 0.4, -0.2, -0.3, -0.5]]))

In [6]:
arg = np.random.randint(-9, 10, (5, 1)) / 10
arg, hidden + arg

(array([[ 0.1],
        [ 0.3],
        [-0.6],
        [ 0.1],
        [ 0.5]]), array([[ 0.8, -0.6, -0.6, -0.7],
        [ 0.6, -0.5,  0.9,  0. ],
        [-0.9, -1. , -0.6, -1.2],
        [ 0.9,  1. ,  0.3,  0.1],
        [ 0.4,  1.2,  0.9,  0.2]]))

In [7]:
arg = np.random.randint(-9, 10, (1, 1)) / 10
arg, hidden + arg

(array([[0.8]]), array([[1.5, 0.1, 0.1, 0. ],
        [1.1, 0. , 1.4, 0.5],
        [0.5, 0.4, 0.8, 0.2],
        [1.6, 1.7, 1. , 0.8],
        [0.7, 1.5, 1.2, 0.5]]))

In [8]:
hidden + 1

array([[1.7, 0.3, 0.3, 0.2],
       [1.3, 0.2, 1.6, 0.7],
       [0.7, 0.6, 1. , 0.4],
       [1.8, 1.9, 1.2, 1. ],
       [0.9, 1.7, 1.4, 0.7]])

In [9]:
1 + hidden

array([[1.7, 0.3, 0.3, 0.2],
       [1.3, 0.2, 1.6, 0.7],
       [0.7, 0.6, 1. , 0.4],
       [1.8, 1.9, 1.2, 1. ],
       [0.9, 1.7, 1.4, 0.7]])

## element wise multiplication

In [10]:
arg = np.random.randint(-9, 10, (5, 4)) / 10
arg, hidden * arg

(array([[-0.1, -0.1, -0.9,  0. ],
        [-0.5, -0.1, -0.6, -0.3],
        [ 0.3, -0.8,  0.3, -0.5],
        [ 0.1,  0.5, -0.4, -0.2],
        [ 0.4,  0.9,  0. , -0.6]]), array([[-0.07,  0.07,  0.63, -0.  ],
        [-0.15,  0.08, -0.36,  0.09],
        [-0.09,  0.32,  0.  ,  0.3 ],
        [ 0.08,  0.45, -0.08, -0.  ],
        [-0.04,  0.63,  0.  ,  0.18]]))

In [11]:
arg = np.random.randint(-9, 10, (1, 4)) / 10
arg, hidden * arg

(array([[-0.8,  0.5,  0.4, -0.7]]), array([[-0.56, -0.35, -0.28,  0.56],
        [-0.24, -0.4 ,  0.24,  0.21],
        [ 0.24, -0.2 ,  0.  ,  0.42],
        [-0.64,  0.45,  0.08, -0.  ],
        [ 0.08,  0.35,  0.16,  0.21]]))

In [12]:
arg = np.random.randint(-9, 10, (5, 1)) / 10
arg, hidden * arg

(array([[-0.4],
        [ 0.9],
        [-0.3],
        [-0.7],
        [ 0.4]]), array([[-0.28,  0.28,  0.28,  0.32],
        [ 0.27, -0.72,  0.54, -0.27],
        [ 0.09,  0.12, -0.  ,  0.18],
        [-0.56, -0.63, -0.14, -0.  ],
        [-0.04,  0.28,  0.16, -0.12]]))

In [13]:
arg = np.random.randint(-9, 10, (1, 1)) / 10
arg, hidden * arg

(array([[0.5]]), array([[ 0.35, -0.35, -0.35, -0.4 ],
        [ 0.15, -0.4 ,  0.3 , -0.15],
        [-0.15, -0.2 ,  0.  , -0.3 ],
        [ 0.4 ,  0.45,  0.1 ,  0.  ],
        [-0.05,  0.35,  0.2 , -0.15]]))

In [14]:
hidden * 2

array([[ 1.4, -1.4, -1.4, -1.6],
       [ 0.6, -1.6,  1.2, -0.6],
       [-0.6, -0.8,  0. , -1.2],
       [ 1.6,  1.8,  0.4,  0. ],
       [-0.2,  1.4,  0.8, -0.6]])

In [15]:
2 * hidden

array([[ 1.4, -1.4, -1.4, -1.6],
       [ 0.6, -1.6,  1.2, -0.6],
       [-0.6, -0.8,  0. , -1.2],
       [ 1.6,  1.8,  0.4,  0. ],
       [-0.2,  1.4,  0.8, -0.6]])

## matrix multiplication

In [16]:
arg = np.random.randint(-9, 10, (4, 5)) / 10
arg, np.matmul(hidden, arg)

(array([[ 0.8,  0.7, -0.5,  0.6, -0.4],
        [-0.8, -0.1, -0.8,  0.6, -0.9],
        [ 0.9,  0.5, -0.8,  0.6, -0.6],
        [ 0.1, -0.4,  0.9,  0.5,  0. ]]),
 array([[ 0.41,  0.53,  0.05, -0.82,  0.77],
        [ 1.39,  0.71, -0.26, -0.09,  0.24],
        [ 0.02,  0.07, -0.07, -0.72,  0.48],
        [ 0.1 ,  0.57, -1.28,  1.14, -1.25],
        [-0.31,  0.18, -1.1 ,  0.45, -0.83]]))

In [17]:
val = np.zeros((hidden.shape[0], arg.shape[1]))
val

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
for row in range(hidden.shape[0]):
    row_v = hidden[row]
    for col in range(arg.shape[1]):
        col_v = arg[:, col]
        val[row][col] = np.dot(row_v, col_v)
val

array([[ 0.41,  0.53,  0.05, -0.82,  0.77],
       [ 1.39,  0.71, -0.26, -0.09,  0.24],
       [ 0.02,  0.07, -0.07, -0.72,  0.48],
       [ 0.1 ,  0.57, -1.28,  1.14, -1.25],
       [-0.31,  0.18, -1.1 ,  0.45, -0.83]])